<template>
  <div class="icon-picker">
    <div class="options">
      <i class="far fa-birthday-cake" v-on:click="$store.state.tempSearch.icon = 'far fa-birthday-cake'"></i>
      <i class="far fa-book" v-on:click="$store.state.tempSearch.icon = 'far fa-book'"></i>
      <i class="far fa-briefcase" v-on:click="$store.state.tempSearch.icon = 'far fa-briefcase'"></i>
      <i class="far fa-building" v-on:click="$store.state.tempSearch.icon = 'far fa-building'"></i>
      <i class="far fa-bullhorn" v-on:click="$store.state.tempSearch.icon = 'far fa-bullhorn'"></i>
      <i class="far fa-bullseye" v-on:click="$store.state.tempSearch.icon = 'far fa-bullseye'"></i>
      <i class="far fa-business-time" v-on:click="$store.state.tempSearch.icon = 'far fa-business-time'"></i>
      <i class="far fa-cabinet-filing" v-on:click="$store.state.tempSearch.icon = 'far fa-cabinet-filing'"></i>
      <i class="far fa-calculator" v-on:click="$store.state.tempSearch.icon = 'far fa-calculator'"></i>
      <i class="far fa-calendar" v-on:click="$store.state.tempSearch.icon = 'far fa-calendar'"></i>
      <i class="far fa-calendar-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-calendar-alt'"></i>
      <i class="far fa-certificate" v-on:click="$store.state.tempSearch.icon = 'far fa-certificate'"></i>
      <i class="far fa-chart-area" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-area'"></i>
      <i class="far fa-chart-bar" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-bar'"></i>
      <i class="far fa-chart-line" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-line'"></i>
      <i class="far fa-chart-line-down" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-line-down'"></i>
      <i class="far fa-chart-network" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-network'"></i>
      <i class="far fa-chart-pie" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-pie'"></i>
      <i class="far fa-chart-pie-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-chart-pie-alt'"></i>
      <i class="far fa-city" v-on:click="$store.state.tempSearch.icon = 'far fa-city'"></i>
      <i class="far fa-clipboard" v-on:click="$store.state.tempSearch.icon = 'far fa-clipboard'"></i>
      <i class="far fa-coffee" v-on:click="$store.state.tempSearch.icon = 'far fa-coffee'"></i>
      <i class="far fa-columns" v-on:click="$store.state.tempSearch.icon = 'far fa-columns'"></i>
      <i class="far fa-compass" v-on:click="$store.state.tempSearch.icon = 'far fa-compass'"></i>
      <i class="far fa-copy" v-on:click="$store.state.tempSearch.icon = 'far fa-copy'"></i>
      <i class="far fa-copyright" v-on:click="$store.state.tempSearch.icon = 'far fa-copyright'"></i>
      <i class="far fa-cut" v-on:click="$store.state.tempSearch.icon = 'far fa-cut'"></i>
      <i class="far fa-edit" v-on:click="$store.state.tempSearch.icon = 'far fa-edit'"></i>
      <i class="far fa-envelope" v-on:click="$store.state.tempSearch.icon = 'far fa-envelope'"></i>
      <i class="far fa-envelope-open" v-on:click="$store.state.tempSearch.icon = 'far fa-envelope-open'"></i>
      <i class="far fa-envelope-square" v-on:click="$store.state.tempSearch.icon = 'far fa-envelope-square'"></i>
      <i class="far fa-eraser" v-on:click="$store.state.tempSearch.icon = 'far fa-eraser'"></i>
      <i class="far fa-fax" v-on:click="$store.state.tempSearch.icon = 'far fa-fax'"></i>
      <i class="far fa-file" v-on:click="$store.state.tempSearch.icon = 'far fa-file'"></i>
      <i class="far fa-file-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-file-alt'"></i>
      <i class="far fa-file-chart-line" v-on:click="$store.state.tempSearch.icon = 'far fa-file-chart-line'"></i>
      <i class="far fa-file-chart-pie" v-on:click="$store.state.tempSearch.icon = 'far fa-file-chart-pie'"></i>
      <i class="far fa-file-spreadsheet" v-on:click="$store.state.tempSearch.icon = 'far fa-file-spreadsheet'"></i>
      <i class="far fa-file-user" v-on:click="$store.state.tempSearch.icon = 'far fa-file-user'"></i>
      <i class="far fa-folder" v-on:click="$store.state.tempSearch.icon = 'far fa-folder'"></i>
      <i class="far fa-folder-minus" v-on:click="$store.state.tempSearch.icon = 'far fa-folder-minus'"></i>
      <i class="far fa-folder-open" v-on:click="$store.state.tempSearch.icon = 'far fa-folder-open'"></i>
      <i class="far fa-folder-plus" v-on:click="$store.state.tempSearch.icon = 'far fa-folder-plus'"></i>
      <i class="far fa-folder-times" v-on:click="$store.state.tempSearch.icon = 'far fa-folder-times'"></i>
      <i class="far fa-folders" v-on:click="$store.state.tempSearch.icon = 'far fa-folders'"></i>
      <i class="far fa-glasses" v-on:click="$store.state.tempSearch.icon = 'far fa-glasses'"></i>
      <i class="far fa-globe" v-on:click="$store.state.tempSearch.icon = 'far fa-globe'"></i>
      <i class="far fa-highlighter" v-on:click="$store.state.tempSearch.icon = 'far fa-highlighter'"></i>
      <i class="far fa-industry" v-on:click="$store.state.tempSearch.icon = 'far fa-industry'"></i>
      <i class="far fa-industry-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-industry-alt'"></i>
      <i class="far fa-keynote" v-on:click="$store.state.tempSearch.icon = 'far fa-keynote'"></i>
      <i class="far fa-landmark" v-on:click="$store.state.tempSearch.icon = 'far fa-landmark'"></i>
      <i class="far fa-marker" v-on:click="$store.state.tempSearch.icon = 'far fa-marker'"></i>
      <i class="far fa-mind-share" v-on:click="$store.state.tempSearch.icon = 'far fa-mind-share'"></i>
      <i class="far fa-paperclip" v-on:click="$store.state.tempSearch.icon = 'far fa-paperclip'"></i>
      <i class="far fa-paste" v-on:click="$store.state.tempSearch.icon = 'far fa-paste'"></i>
      <i class="far fa-pen" v-on:click="$store.state.tempSearch.icon = 'far fa-pen'"></i>
      <i class="far fa-pen-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-pen-alt'"></i>
      <i class="far fa-pen-fancy" v-on:click="$store.state.tempSearch.icon = 'far fa-pen-fancy'"></i>
      <i class="far fa-pen-nib" v-on:click="$store.state.tempSearch.icon = 'far fa-pen-nib'"></i>
      <i class="far fa-pen-square" v-on:click="$store.state.tempSearch.icon = 'far fa-pen-square'"></i>
      <i class="far fa-pencil" v-on:click="$store.state.tempSearch.icon = 'far fa-pencil'"></i>
      <i class="far fa-pencil-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-pencil-alt'"></i>
      <i class="far fa-percent" v-on:click="$store.state.tempSearch.icon = 'far fa-percent'"></i>
      <i class="far fa-phone" v-on:click="$store.state.tempSearch.icon = 'far fa-phone'"></i>
      <i class="far fa-phone-office" v-on:click="$store.state.tempSearch.icon = 'far fa-phone-office'"></i>
      <i class="far fa-phone-slash" v-on:click="$store.state.tempSearch.icon = 'far fa-phone-slash'"></i>
      <i class="far fa-phone-square" v-on:click="$store.state.tempSearch.icon = 'far fa-phone-square'"></i>
      <i class="far fa-phone-volume" v-on:click="$store.state.tempSearch.icon = 'far fa-phone-volume'"></i>
      <i class="far fa-podium" v-on:click="$store.state.tempSearch.icon = 'far fa-podium'"></i>
      <i class="far fa-presentation" v-on:click="$store.state.tempSearch.icon = 'far fa-presentation'"></i>
      <i class="far fa-print" v-on:click="$store.state.tempSearch.icon = 'far fa-print'"></i>
      <i class="far fa-print-slash" v-on:click="$store.state.tempSearch.icon = 'far fa-print-slash'"></i>
      <i class="far fa-project-diagram" v-on:click="$store.state.tempSearch.icon = 'far fa-project-diagram'"></i>
      <i class="far fa-registered" v-on:click="$store.state.tempSearch.icon = 'far fa-registered'"></i>
      <i class="far fa-save" v-on:click="$store.state.tempSearch.icon = 'far fa-save'"></i>
      <i class="far fa-shredder" v-on:click="$store.state.tempSearch.icon = 'far fa-shredder'"></i>
      <i class="far fa-sitemap" v-on:click="$store.state.tempSearch.icon = 'far fa-sitemap'"></i>
      <i class="far fa-socks" v-on:click="$store.state.tempSearch.icon = 'far fa-socks'"></i>
      <i class="far fa-sticky-note" v-on:click="$store.state.tempSearch.icon = 'far fa-sticky-note'"></i>
      <i class="far fa-stream" v-on:click="$store.state.tempSearch.icon = 'far fa-stream'"></i>
      <i class="far fa-table" v-on:click="$store.state.tempSearch.icon = 'far fa-table'"></i>
      <i class="far fa-tag" v-on:click="$store.state.tempSearch.icon = 'far fa-tag'"></i>
      <i class="far fa-tags" v-on:click="$store.state.tempSearch.icon = 'far fa-tags'"></i>
      <i class="far fa-tasks" v-on:click="$store.state.tempSearch.icon = 'far fa-tasks'"></i>
      <i class="far fa-thumbtack" v-on:click="$store.state.tempSearch.icon = 'far fa-thumbtack'"></i>
      <i class="far fa-trademark" v-on:click="$store.state.tempSearch.icon = 'far fa-trademark'"></i>
      <i class="far fa-user-chart" v-on:click="$store.state.tempSearch.icon = 'far fa-user-chart'"></i>
      <i class="far fa-wallet" v-on:click="$store.state.tempSearch.icon = 'far fa-wallet'"></i>
      <i class="far fa-square" v-on:click="$store.state.tempSearch.icon = 'far fa-square'"></i>
      <i class="far fa-check" v-on:click="$store.state.tempSearch.icon = 'far fa-check'"></i>
      <i class="far fa-user" v-on:click="$store.state.tempSearch.icon = 'far fa-user'"></i>
      <i class="far fa-users" v-on:click="$store.state.tempSearch.icon = 'far fa-users'"></i>
      <i class="far fa-at" v-on:click="$store.state.tempSearch.icon = 'far fa-at'"></i>
      <i class="far fa-bell" v-on:click="$store.state.tempSearch.icon = 'far fa-bell'"></i>
      <i class="far fa-camera-retro" v-on:click="$store.state.tempSearch.icon = 'far fa-camera-retro'"></i>
      <i class="far fa-code" v-on:click="$store.state.tempSearch.icon = 'far fa-code'"></i>
      <i class="far fa-utensils" v-on:click="$store.state.tempSearch.icon = 'far fa-utensils'"></i>
      <i class="far fa-desktop" v-on:click="$store.state.tempSearch.icon = 'far fa-desktop'"></i>
      <i class="far fa-file-code" v-on:click="$store.state.tempSearch.icon = 'far fa-file-code'"></i>
      <i class="far fa-file-image" v-on:click="$store.state.tempSearch.icon = 'far fa-file-image'"></i>
      <i class="far fa-film" v-on:click="$store.state.tempSearch.icon = 'far fa-film'"></i>
      <i class="far fa-filter" v-on:click="$store.state.tempSearch.icon = 'far fa-filter'"></i>
      <i class="far fa-gamepad" v-on:click="$store.state.tempSearch.icon = 'far fa-gamepad'"></i>
      <i class="far fa-glass-martini" v-on:click="$store.state.tempSearch.icon = 'far fa-glass-martini'"></i>
      <i class="far fa-hashtag" v-on:click="$store.state.tempSearch.icon = 'far fa-hashtag'"></i>
      <i class="far fa-headphones" v-on:click="$store.state.tempSearch.icon = 'far fa-headphones'"></i>
      <i class="far fa-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-heart'"></i>
      <i class="far fa-heartbeat" v-on:click="$store.state.tempSearch.icon = 'far fa-heartbeat'"></i>
      <i class="far fa-history" v-on:click="$store.state.tempSearch.icon = 'far fa-history'"></i>
      <i class="far fa-home" v-on:click="$store.state.tempSearch.icon = 'far fa-home'"></i>
      <i class="far fa-image" v-on:click="$store.state.tempSearch.icon = 'far fa-image'"></i>
      <i class="far fa-inbox" v-on:click="$store.state.tempSearch.icon = 'far fa-inbox'"></i>
      <i class="far fa-map-marker" v-on:click="$store.state.tempSearch.icon = 'far fa-map-marker'"></i>
      <i class="far fa-dollar-sign" v-on:click="$store.state.tempSearch.icon = 'far fa-dollar-sign'"></i>
      <i class="far fa-music" v-on:click="$store.state.tempSearch.icon = 'far fa-music'"></i>
      <i class="far fa-paw" v-on:click="$store.state.tempSearch.icon = 'far fa-paw'"></i>
      <i class="far fa-puzzle-piece" v-on:click="$store.state.tempSearch.icon = 'far fa-puzzle-piece'"></i>
      <i class="far fa-smile" v-on:click="$store.state.tempSearch.icon = 'far fa-smile'"></i>
      <i class="far fa-futbol" v-on:click="$store.state.tempSearch.icon = 'far fa-futbol'"></i>
      <i class="far fa-comment-dots" v-on:click="$store.state.tempSearch.icon = 'far fa-comment-dots'"></i>
      <i class="far fa-thumbs-up" v-on:click="$store.state.tempSearch.icon = 'far fa-thumbs-up'"></i>
      <i class="far fa-tree" v-on:click="$store.state.tempSearch.icon = 'far fa-tree'"></i>
      <i class="far fa-trophy" v-on:click="$store.state.tempSearch.icon = 'far fa-trophy'"></i>
      <i class="far fa-tv" v-on:click="$store.state.tempSearch.icon = 'far fa-tv'"></i>
      <i class="far fa-video" v-on:click="$store.state.tempSearch.icon = 'far fa-video'"></i>
      <i class="far fa-wrench" v-on:click="$store.state.tempSearch.icon = 'far fa-wrench'"></i>
      <i class="far fa-dog-leashed" v-on:click="$store.state.tempSearch.icon = 'far fa-dog-leashed'"></i>
      <i class="far fa-american-sign-language-interpreting" v-on:click="$store.state.tempSearch.icon = 'far fa-american-sign-language-interpreting'"></i>
      <i class="far fa-recycle" v-on:click="$store.state.tempSearch.icon = 'far fa-recycle'"></i>
      <i class="far fa-random" v-on:click="$store.state.tempSearch.icon = 'far fa-random'"></i>
      <i class="far fa-play" v-on:click="$store.state.tempSearch.icon = 'far fa-play'"></i>
      <i class="far fa-triangle" v-on:click="$store.state.tempSearch.icon = 'far fa-triangle'"></i>
      <i class="far fa-undo-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-undo-alt'"></i>
      <i class="far fa-hand-pointer" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-pointer'"></i>
      <i class="far fa-inbox-in" v-on:click="$store.state.tempSearch.icon = 'far fa-inbox-in'"></i>
      <i class="far fa-inbox-out" v-on:click="$store.state.tempSearch.icon = 'far fa-inbox-out'"></i>
      <i class="far fa-podcast" v-on:click="$store.state.tempSearch.icon = 'far fa-podcast'"></i>
      <i class="far fa-microphone-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-microphone-alt'"></i>
      <i class="far fa-broadcast-tower" v-on:click="$store.state.tempSearch.icon = 'far fa-broadcast-tower'"></i>
      <i class="far fa-scrubber" v-on:click="$store.state.tempSearch.icon = 'far fa-scrubber'"></i>
      <i class="far fa-repeat-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-repeat-alt'"></i>
      <i class="far fa-rss" v-on:click="$store.state.tempSearch.icon = 'far fa-rss'"></i>
      <i class="far fa-steering-wheel" v-on:click="$store.state.tempSearch.icon = 'far fa-steering-wheel'"></i>
      <i class="far fa-motorcycle" v-on:click="$store.state.tempSearch.icon = 'far fa-motorcycle'"></i>
      <i class="far fa-shuttle-van" v-on:click="$store.state.tempSearch.icon = 'far fa-shuttle-van'"></i>
      <i class="far fa-anchor" v-on:click="$store.state.tempSearch.icon = 'far fa-anchor'"></i>
      <i class="far fa-atom" v-on:click="$store.state.tempSearch.icon = 'far fa-atom'"></i>
      <i class="far fa-bed" v-on:click="$store.state.tempSearch.icon = 'far fa-bed'"></i>
      <i class="far fa-bath" v-on:click="$store.state.tempSearch.icon = 'far fa-bath'"></i>
      <i class="far fa-bolt" v-on:click="$store.state.tempSearch.icon = 'far fa-bolt'"></i>
      <i class="far fa-car" v-on:click="$store.state.tempSearch.icon = 'far fa-car'"></i>
      <i class="far fa-child" v-on:click="$store.state.tempSearch.icon = 'far fa-child'"></i>
      <i class="far fa-clouds" v-on:click="$store.state.tempSearch.icon = 'far fa-clouds'"></i>
      <i class="far fa-hourglass-half" v-on:click="$store.state.tempSearch.icon = 'far fa-hourglass-half'"></i>
      <i class="far fa-alicorn" v-on:click="$store.state.tempSearch.icon = 'far fa-alicorn'"></i>
      <i class="far fa-badger-honey" v-on:click="$store.state.tempSearch.icon = 'far fa-badger-honey'"></i>
      <i class="far fa-bat" v-on:click="$store.state.tempSearch.icon = 'far fa-bat'"></i>
      <i class="far fa-cat" v-on:click="$store.state.tempSearch.icon = 'far fa-cat'"></i>
      <i class="far fa-cow" v-on:click="$store.state.tempSearch.icon = 'far fa-cow'"></i>
      <i class="far fa-crow" v-on:click="$store.state.tempSearch.icon = 'far fa-crow'"></i>
      <i class="far fa-deer" v-on:click="$store.state.tempSearch.icon = 'far fa-deer'"></i>
      <i class="far fa-deer-rudolph" v-on:click="$store.state.tempSearch.icon = 'far fa-deer-rudolph'"></i>
      <i class="far fa-dog" v-on:click="$store.state.tempSearch.icon = 'far fa-dog'"></i>
      <i class="far fa-dove" v-on:click="$store.state.tempSearch.icon = 'far fa-dove'"></i>
      <i class="far fa-dragon" v-on:click="$store.state.tempSearch.icon = 'far fa-dragon'"></i>
      <i class="far fa-duck" v-on:click="$store.state.tempSearch.icon = 'far fa-duck'"></i>
      <i class="far fa-elephant" v-on:click="$store.state.tempSearch.icon = 'far fa-elephant'"></i>
      <i class="far fa-feather" v-on:click="$store.state.tempSearch.icon = 'far fa-feather'"></i>
      <i class="far fa-feather-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-feather-alt'"></i>
      <i class="far fa-fish" v-on:click="$store.state.tempSearch.icon = 'far fa-fish'"></i>
      <i class="far fa-frog" v-on:click="$store.state.tempSearch.icon = 'far fa-frog'"></i>
      <i class="far fa-hippo" v-on:click="$store.state.tempSearch.icon = 'far fa-hippo'"></i>
      <i class="far fa-horse" v-on:click="$store.state.tempSearch.icon = 'far fa-horse'"></i>
      <i class="far fa-horse-head" v-on:click="$store.state.tempSearch.icon = 'far fa-horse-head'"></i>
      <i class="far fa-kiwi-bird" v-on:click="$store.state.tempSearch.icon = 'far fa-kiwi-bird'"></i>
      <i class="far fa-monkey" v-on:click="$store.state.tempSearch.icon = 'far fa-monkey'"></i>
      <i class="far fa-narwhal" v-on:click="$store.state.tempSearch.icon = 'far fa-narwhal'"></i>
      <i class="far fa-otter" v-on:click="$store.state.tempSearch.icon = 'far fa-otter'"></i>
      <i class="far fa-paw-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-paw-alt'"></i>
      <i class="far fa-paw-claws" v-on:click="$store.state.tempSearch.icon = 'far fa-paw-claws'"></i>
      <i class="far fa-pegasus" v-on:click="$store.state.tempSearch.icon = 'far fa-pegasus'"></i>
      <i class="far fa-pig" v-on:click="$store.state.tempSearch.icon = 'far fa-pig'"></i>
      <i class="far fa-rabbit" v-on:click="$store.state.tempSearch.icon = 'far fa-rabbit'"></i>
      <i class="far fa-rabbit-fast" v-on:click="$store.state.tempSearch.icon = 'far fa-rabbit-fast'"></i>
      <i class="far fa-ram" v-on:click="$store.state.tempSearch.icon = 'far fa-ram'"></i>
      <i class="far fa-sheep" v-on:click="$store.state.tempSearch.icon = 'far fa-sheep'"></i>
      <i class="far fa-snake" v-on:click="$store.state.tempSearch.icon = 'far fa-snake'"></i>
      <i class="far fa-spider" v-on:click="$store.state.tempSearch.icon = 'far fa-spider'"></i>
      <i class="far fa-spider-black-widow" v-on:click="$store.state.tempSearch.icon = 'far fa-spider-black-widow'"></i>
      <i class="far fa-squirrel" v-on:click="$store.state.tempSearch.icon = 'far fa-squirrel'"></i>
      <i class="far fa-turtle" v-on:click="$store.state.tempSearch.icon = 'far fa-turtle'"></i>
      <i class="far fa-unicorn" v-on:click="$store.state.tempSearch.icon = 'far fa-unicorn'"></i>
      <i class="far fa-whale" v-on:click="$store.state.tempSearch.icon = 'far fa-whale'"></i>
      <i class="far fa-acorn" v-on:click="$store.state.tempSearch.icon = 'far fa-acorn'"></i>
      <i class="far fa-apple-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-apple-alt'"></i>
      <i class="far fa-apple-crate" v-on:click="$store.state.tempSearch.icon = 'far fa-apple-crate'"></i>
      <i class="far fa-axe" v-on:click="$store.state.tempSearch.icon = 'far fa-axe'"></i>
      <i class="far fa-campfire" v-on:click="$store.state.tempSearch.icon = 'far fa-campfire'"></i>
      <i class="far fa-campground" v-on:click="$store.state.tempSearch.icon = 'far fa-campground'"></i>
      <i class="far fa-cloud-sun" v-on:click="$store.state.tempSearch.icon = 'far fa-cloud-sun'"></i>
      <i class="far fa-coffee-togo" v-on:click="$store.state.tempSearch.icon = 'far fa-coffee-togo'"></i>
      <i class="far fa-corn" v-on:click="$store.state.tempSearch.icon = 'far fa-corn'"></i>
      <i class="far fa-drumstick" v-on:click="$store.state.tempSearch.icon = 'far fa-drumstick'"></i>
      <i class="far fa-drumstick-bite" v-on:click="$store.state.tempSearch.icon = 'far fa-drumstick-bite'"></i>
      <i class="far fa-football-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-football-ball'"></i>
      <i class="far fa-hiking" v-on:click="$store.state.tempSearch.icon = 'far fa-hiking'"></i>
      <i class="far fa-kite" v-on:click="$store.state.tempSearch.icon = 'far fa-kite'"></i>
      <i class="far fa-leaf-maple" v-on:click="$store.state.tempSearch.icon = 'far fa-leaf-maple'"></i>
      <i class="far fa-leaf-oak" v-on:click="$store.state.tempSearch.icon = 'far fa-leaf-oak'"></i>
      <i class="far fa-mountain" v-on:click="$store.state.tempSearch.icon = 'far fa-mountain'"></i>
      <i class="far fa-mountains" v-on:click="$store.state.tempSearch.icon = 'far fa-mountains'"></i>
      <i class="far fa-pie" v-on:click="$store.state.tempSearch.icon = 'far fa-pie'"></i>
      <i class="far fa-pumpkin" v-on:click="$store.state.tempSearch.icon = 'far fa-pumpkin'"></i>
      <i class="far fa-shovel" v-on:click="$store.state.tempSearch.icon = 'far fa-shovel'"></i>
      <i class="far fa-tractor" v-on:click="$store.state.tempSearch.icon = 'far fa-tractor'"></i>
      <i class="far fa-tree-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-tree-alt'"></i>
      <i class="far fa-trees" v-on:click="$store.state.tempSearch.icon = 'far fa-trees'"></i>
      <i class="far fa-turkey" v-on:click="$store.state.tempSearch.icon = 'far fa-turkey'"></i>
      <i class="far fa-wheat" v-on:click="$store.state.tempSearch.icon = 'far fa-wheat'"></i>
      <i class="far fa-wind" v-on:click="$store.state.tempSearch.icon = 'far fa-wind'"></i>
      <i class="far fa-allergies" v-on:click="$store.state.tempSearch.icon = 'far fa-allergies'"></i>
      <i class="far fa-ambulance" v-on:click="$store.state.tempSearch.icon = 'far fa-ambulance'"></i>
      <i class="far fa-angel" v-on:click="$store.state.tempSearch.icon = 'far fa-angel'"></i>
      <i class="far fa-angry" v-on:click="$store.state.tempSearch.icon = 'far fa-angry'"></i>
      <i class="far fa-ankh" v-on:click="$store.state.tempSearch.icon = 'far fa-ankh'"></i>
      <i class="far fa-archway" v-on:click="$store.state.tempSearch.icon = 'far fa-archway'"></i>
      <i class="far fa-atom-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-atom-alt'"></i>
      <i class="far fa-award" v-on:click="$store.state.tempSearch.icon = 'far fa-award'"></i>
      <i class="far fa-axe-battle" v-on:click="$store.state.tempSearch.icon = 'far fa-axe-battle'"></i>
      <i class="far fa-baby-carriage" v-on:click="$store.state.tempSearch.icon = 'far fa-baby-carriage'"></i>
      <i class="far fa-ball-pile" v-on:click="$store.state.tempSearch.icon = 'far fa-ball-pile'"></i>
      <i class="far fa-barcode" v-on:click="$store.state.tempSearch.icon = 'far fa-barcode'"></i>
      <i class="far fa-baseball" v-on:click="$store.state.tempSearch.icon = 'far fa-baseball'"></i>
      <i class="far fa-baseball-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-baseball-ball'"></i>
      <i class="far fa-basketball-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-basketball-ball'"></i>
      <i class="far fa-basketball-hoop" v-on:click="$store.state.tempSearch.icon = 'far fa-basketball-hoop'"></i>
      <i class="far fa-bells" v-on:click="$store.state.tempSearch.icon = 'far fa-bells'"></i>
      <i class="far fa-bezier-curve" v-on:click="$store.state.tempSearch.icon = 'far fa-bezier-curve'"></i>
      <i class="far fa-bible" v-on:click="$store.state.tempSearch.icon = 'far fa-bible'"></i>
      <i class="far fa-bicycle" v-on:click="$store.state.tempSearch.icon = 'far fa-bicycle'"></i>
      <i class="far fa-binoculars" v-on:click="$store.state.tempSearch.icon = 'far fa-binoculars'"></i>
      <i class="far fa-biohazard" v-on:click="$store.state.tempSearch.icon = 'far fa-biohazard'"></i>
      <i class="far fa-blender" v-on:click="$store.state.tempSearch.icon = 'far fa-blender'"></i>
      <i class="far fa-bomb" v-on:click="$store.state.tempSearch.icon = 'far fa-bomb'"></i>
      <i class="far fa-bone" v-on:click="$store.state.tempSearch.icon = 'far fa-bone'"></i>
      <i class="far fa-bong" v-on:click="$store.state.tempSearch.icon = 'far fa-bong'"></i>
      <i class="far fa-book-dead" v-on:click="$store.state.tempSearch.icon = 'far fa-book-dead'"></i>
      <i class="far fa-book-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-book-heart'"></i>
      <i class="far fa-book-spells" v-on:click="$store.state.tempSearch.icon = 'far fa-book-spells'"></i>
      <i class="far fa-bookmark" v-on:click="$store.state.tempSearch.icon = 'far fa-bookmark'"></i>
      <i class="far fa-boot" v-on:click="$store.state.tempSearch.icon = 'far fa-boot'"></i>
      <i class="far fa-bow-arrow" v-on:click="$store.state.tempSearch.icon = 'far fa-bow-arrow'"></i>
      <i class="far fa-bowling-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-bowling-ball'"></i>
      <i class="far fa-bowling-pins" v-on:click="$store.state.tempSearch.icon = 'far fa-bowling-pins'"></i>
      <i class="far fa-box-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-box-heart'"></i>
      <i class="far fa-box-usd" v-on:click="$store.state.tempSearch.icon = 'far fa-box-usd'"></i>
      <i class="far fa-boxing-glove" v-on:click="$store.state.tempSearch.icon = 'far fa-boxing-glove'"></i>
      <i class="far fa-brain" v-on:click="$store.state.tempSearch.icon = 'far fa-brain'"></i>
      <i class="far fa-broom" v-on:click="$store.state.tempSearch.icon = 'far fa-broom'"></i>
      <i class="far fa-bug" v-on:click="$store.state.tempSearch.icon = 'far fa-bug'"></i>
      <i class="far fa-burn" v-on:click="$store.state.tempSearch.icon = 'far fa-burn'"></i>
      <i class="far fa-bus" v-on:click="$store.state.tempSearch.icon = 'far fa-bus'"></i>
      <i class="far fa-bus-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-bus-alt'"></i>
      <i class="far fa-camera-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-camera-alt'"></i>
      <i class="far fa-candle-holder" v-on:click="$store.state.tempSearch.icon = 'far fa-candle-holder'"></i>
      <i class="far fa-candy-cane" v-on:click="$store.state.tempSearch.icon = 'far fa-candy-cane'"></i>
      <i class="far fa-candy-corn" v-on:click="$store.state.tempSearch.icon = 'far fa-candy-corn'"></i>
      <i class="far fa-cannabis" v-on:click="$store.state.tempSearch.icon = 'far fa-cannabis'"></i>
      <i class="far fa-capsules" v-on:click="$store.state.tempSearch.icon = 'far fa-capsules'"></i>
      <i class="far fa-car-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-car-alt'"></i>
      <i class="far fa-car-bump" v-on:click="$store.state.tempSearch.icon = 'far fa-car-bump'"></i>
      <i class="far fa-car-crash" v-on:click="$store.state.tempSearch.icon = 'far fa-car-crash'"></i>
      <i class="far fa-car-side" v-on:click="$store.state.tempSearch.icon = 'far fa-car-side'"></i>
      <i class="far fa-car-tilt" v-on:click="$store.state.tempSearch.icon = 'far fa-car-tilt'"></i>
      <i class="far fa-carrot" v-on:click="$store.state.tempSearch.icon = 'far fa-carrot'"></i>
      <i class="far fa-cauldron" v-on:click="$store.state.tempSearch.icon = 'far fa-cauldron'"></i>
      <i class="far fa-chess" v-on:click="$store.state.tempSearch.icon = 'far fa-chess'"></i>
      <i class="far fa-chimney" v-on:click="$store.state.tempSearch.icon = 'far fa-chimney'"></i>
      <i class="far fa-church" v-on:click="$store.state.tempSearch.icon = 'far fa-church'"></i>
      <i class="far fa-claw-marks" v-on:click="$store.state.tempSearch.icon = 'far fa-claw-marks'"></i>
      <i class="far fa-cloud" v-on:click="$store.state.tempSearch.icon = 'far fa-cloud'"></i>
      <i class="far fa-cloud-moon" v-on:click="$store.state.tempSearch.icon = 'far fa-cloud-moon'"></i>
      <i class="far fa-club" v-on:click="$store.state.tempSearch.icon = 'far fa-club'"></i>
      <i class="far fa-code-branch" v-on:click="$store.state.tempSearch.icon = 'far fa-code-branch'"></i>
      <i class="far fa-coffin" v-on:click="$store.state.tempSearch.icon = 'far fa-coffin'"></i>
      <i class="far fa-cogs" v-on:click="$store.state.tempSearch.icon = 'far fa-cogs'"></i>
      <i class="far fa-comment" v-on:click="$store.state.tempSearch.icon = 'far fa-comment'"></i>
      <i class="far fa-comment-alt-lines" v-on:click="$store.state.tempSearch.icon = 'far fa-comment-alt-lines'"></i>
      <i class="far fa-comment-alt-smile" v-on:click="$store.state.tempSearch.icon = 'far fa-comment-alt-smile'"></i>
      <i class="far fa-compact-disc" v-on:click="$store.state.tempSearch.icon = 'far fa-compact-disc'"></i>
      <i class="far fa-cookie-bite" v-on:click="$store.state.tempSearch.icon = 'far fa-cookie-bite'"></i>
      <i class="far fa-cricket" v-on:click="$store.state.tempSearch.icon = 'far fa-cricket'"></i>
      <i class="far fa-cross" v-on:click="$store.state.tempSearch.icon = 'far fa-cross'"></i>
      <i class="far fa-crosshairs" v-on:click="$store.state.tempSearch.icon = 'far fa-crosshairs'"></i>
      <i class="far fa-curling" v-on:click="$store.state.tempSearch.icon = 'far fa-curling'"></i>
      <i class="far fa-dagger" v-on:click="$store.state.tempSearch.icon = 'far fa-dagger'"></i>
      <i class="far fa-database" v-on:click="$store.state.tempSearch.icon = 'far fa-database'"></i>
      <i class="far fa-democrat" v-on:click="$store.state.tempSearch.icon = 'far fa-democrat'"></i>
      <i class="far fa-dharmachakra" v-on:click="$store.state.tempSearch.icon = 'far fa-dharmachakra'"></i>
      <i class="far fa-diamond" v-on:click="$store.state.tempSearch.icon = 'far fa-diamond'"></i>
      <i class="far fa-dice" v-on:click="$store.state.tempSearch.icon = 'far fa-dice'"></i>
      <i class="far fa-dice-d10" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d10'"></i>
      <i class="far fa-dice-d12" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d12'"></i>
      <i class="far fa-dice-d20" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d20'"></i>
      <i class="far fa-dice-d4" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d4'"></i>
      <i class="far fa-dice-d6" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d6'"></i>
      <i class="far fa-dice-d8" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-d8'"></i>
      <i class="far fa-dice-five" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-five'"></i>
      <i class="far fa-dice-four" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-four'"></i>
      <i class="far fa-dice-one" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-one'"></i>
      <i class="far fa-dice-six" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-six'"></i>
      <i class="far fa-dice-three" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-three'"></i>
      <i class="far fa-dice-two" v-on:click="$store.state.tempSearch.icon = 'far fa-dice-two'"></i>
      <i class="far fa-dizzy" v-on:click="$store.state.tempSearch.icon = 'far fa-dizzy'"></i>
      <i class="far fa-dna" v-on:click="$store.state.tempSearch.icon = 'far fa-dna'"></i>
      <i class="far fa-donate" v-on:click="$store.state.tempSearch.icon = 'far fa-donate'"></i>
      <i class="far fa-drafting-compass" v-on:click="$store.state.tempSearch.icon = 'far fa-drafting-compass'"></i>
      <i class="far fa-dreidel" v-on:click="$store.state.tempSearch.icon = 'far fa-dreidel'"></i>
      <i class="far fa-drum" v-on:click="$store.state.tempSearch.icon = 'far fa-drum'"></i>
      <i class="far fa-drum-steelpan" v-on:click="$store.state.tempSearch.icon = 'far fa-drum-steelpan'"></i>
      <i class="far fa-dumbbell" v-on:click="$store.state.tempSearch.icon = 'far fa-dumbbell'"></i>
      <i class="far fa-dungeon" v-on:click="$store.state.tempSearch.icon = 'far fa-dungeon'"></i>
      <i class="far fa-ear" v-on:click="$store.state.tempSearch.icon = 'far fa-ear'"></i>
      <i class="far fa-eye" v-on:click="$store.state.tempSearch.icon = 'far fa-eye'"></i>
      <i class="far fa-eye-evil" v-on:click="$store.state.tempSearch.icon = 'far fa-eye-evil'"></i>
      <i class="far fa-circle" v-on:click="$store.state.tempSearch.icon = 'far fa-circle'"></i>
      <i class="fas fa-circle" v-on:click="$store.state.tempSearch.icon = 'fas fa-circle'"></i>
      <i class="far fa-female" v-on:click="$store.state.tempSearch.icon = 'far fa-female'"></i>
      <i class="far fa-field-hockey" v-on:click="$store.state.tempSearch.icon = 'far fa-field-hockey'"></i>
      <i class="far fa-fighter-jet" v-on:click="$store.state.tempSearch.icon = 'far fa-fighter-jet'"></i>
      <i class="far fa-fingerprint" v-on:click="$store.state.tempSearch.icon = 'far fa-fingerprint'"></i>
      <i class="far fa-fire-extinguisher" v-on:click="$store.state.tempSearch.icon = 'far fa-fire-extinguisher'"></i>
      <i class="far fa-fireplace" v-on:click="$store.state.tempSearch.icon = 'far fa-fireplace'"></i>
      <i class="far fa-fist-raised" v-on:click="$store.state.tempSearch.icon = 'far fa-fist-raised'"></i>
      <i class="far fa-flag-checkered" v-on:click="$store.state.tempSearch.icon = 'far fa-flag-checkered'"></i>
      <i class="far fa-flame" v-on:click="$store.state.tempSearch.icon = 'far fa-flame'"></i>
      <i class="far fa-flask-poison" v-on:click="$store.state.tempSearch.icon = 'far fa-flask-poison'"></i>
      <i class="far fa-flask-potion" v-on:click="$store.state.tempSearch.icon = 'far fa-flask-potion'"></i>
      <i class="far fa-flushed" v-on:click="$store.state.tempSearch.icon = 'far fa-flushed'"></i>
      <i class="fab fa-font-awesome" v-on:click="$store.state.tempSearch.icon = 'fab fa-font-awesome'"></i>
      <i class="fab fa-font-awesome-alt" v-on:click="$store.state.tempSearch.icon = 'fab fa-font-awesome-alt'"></i>
      <i class="far fa-football-helmet" v-on:click="$store.state.tempSearch.icon = 'far fa-football-helmet'"></i>
      <i class="far fa-forklift" v-on:click="$store.state.tempSearch.icon = 'far fa-forklift'"></i>
      <i class="far fa-frosty-head" v-on:click="$store.state.tempSearch.icon = 'far fa-frosty-head'"></i>
      <i class="far fa-frown" v-on:click="$store.state.tempSearch.icon = 'far fa-frown'"></i>
      <i class="far fa-frown-open" v-on:click="$store.state.tempSearch.icon = 'far fa-frown-open'"></i>
      <i class="fab fa-galactic-republic" v-on:click="$store.state.tempSearch.icon = 'fab fa-galactic-republic'"></i>
      <i class="fab fa-galactic-senate" v-on:click="$store.state.tempSearch.icon = 'fab fa-galactic-senate'"></i>
      <i class="far fa-gas-pump" v-on:click="$store.state.tempSearch.icon = 'far fa-gas-pump'"></i>
      <i class="far fa-gem" v-on:click="$store.state.tempSearch.icon = 'far fa-gem'"></i>
      <i class="far fa-genderless" v-on:click="$store.state.tempSearch.icon = 'far fa-genderless'"></i>
      <i class="far fa-ghost" v-on:click="$store.state.tempSearch.icon = 'far fa-ghost'"></i>
      <i class="far fa-gift" v-on:click="$store.state.tempSearch.icon = 'far fa-gift'"></i>
      <i class="far fa-gifts" v-on:click="$store.state.tempSearch.icon = 'far fa-gifts'"></i>
      <i class="far fa-gingerbread-man" v-on:click="$store.state.tempSearch.icon = 'far fa-gingerbread-man'"></i>
      <i class="far fa-glass-champagne" v-on:click="$store.state.tempSearch.icon = 'far fa-glass-champagne'"></i>
      <i class="far fa-glass-cheers" v-on:click="$store.state.tempSearch.icon = 'far fa-glass-cheers'"></i>
      <i class="far fa-glass-martini-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-glass-martini-alt'"></i>
      <i class="far fa-glass-whiskey-rocks" v-on:click="$store.state.tempSearch.icon = 'far fa-glass-whiskey-rocks'"></i>
      <i class="far fa-globe-africa" v-on:click="$store.state.tempSearch.icon = 'far fa-globe-africa'"></i>
      <i class="far fa-globe-americas" v-on:click="$store.state.tempSearch.icon = 'far fa-globe-americas'"></i>
      <i class="far fa-globe-asia" v-on:click="$store.state.tempSearch.icon = 'far fa-globe-asia'"></i>
      <i class="far fa-globe-europe" v-on:click="$store.state.tempSearch.icon = 'far fa-globe-europe'"></i>
      <i class="far fa-globe-snow" v-on:click="$store.state.tempSearch.icon = 'far fa-globe-snow'"></i>
      <i class="far fa-golf-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-golf-ball'"></i>
      <i class="far fa-golf-club" v-on:click="$store.state.tempSearch.icon = 'far fa-golf-club'"></i>
      <i class="far fa-gopuram" v-on:click="$store.state.tempSearch.icon = 'far fa-gopuram'"></i>
      <i class="far fa-grimace" v-on:click="$store.state.tempSearch.icon = 'far fa-grimace'"></i>
      <i class="far fa-grin" v-on:click="$store.state.tempSearch.icon = 'far fa-grin'"></i>
      <i class="far fa-grin-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-alt'"></i>
      <i class="far fa-grin-beam" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-beam'"></i>
      <i class="far fa-grin-beam-sweat" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-beam-sweat'"></i>
      <i class="far fa-grin-hearts" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-hearts'"></i>
      <i class="far fa-grin-squint" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-squint'"></i>
      <i class="far fa-grin-squint-tears" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-squint-tears'"></i>
      <i class="far fa-grin-stars" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-stars'"></i>
      <i class="far fa-grin-tears" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-tears'"></i>
      <i class="far fa-grin-tongue" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-tongue'"></i>
      <i class="far fa-grin-tongue-squint" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-tongue-squint'"></i>
      <i class="far fa-grin-tongue-wink" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-tongue-wink'"></i>
      <i class="far fa-grin-wink" v-on:click="$store.state.tempSearch.icon = 'far fa-grin-wink'"></i>
      <i class="far fa-h-square" v-on:click="$store.state.tempSearch.icon = 'far fa-h-square'"></i>
      <i class="far fa-hammer-war" v-on:click="$store.state.tempSearch.icon = 'far fa-hammer-war'"></i>
      <i class="far fa-hamsa" v-on:click="$store.state.tempSearch.icon = 'far fa-hamsa'"></i>
      <i class="far fa-hand-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-heart'"></i>
      <i class="far fa-hand-holding-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-holding-heart'"></i>
      <i class="far fa-hand-holding-magic" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-holding-magic'"></i>
      <i class="far fa-hand-holding-seedling" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-holding-seedling'"></i>
      <i class="far fa-hand-holding-usd" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-holding-usd'"></i>
      <i class="far fa-hand-holding-water" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-holding-water'"></i>
      <i class="far fa-hand-spock" v-on:click="$store.state.tempSearch.icon = 'far fa-hand-spock'"></i>
      <i class="far fa-hands-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-hands-heart'"></i>
      <i class="far fa-hands-helping" v-on:click="$store.state.tempSearch.icon = 'far fa-hands-helping'"></i>
      <i class="far fa-hands-usd" v-on:click="$store.state.tempSearch.icon = 'far fa-hands-usd'"></i>
      <i class="far fa-handshake" v-on:click="$store.state.tempSearch.icon = 'far fa-handshake'"></i>
      <i class="far fa-handshake-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-handshake-alt'"></i>
      <i class="far fa-hanukiah" v-on:click="$store.state.tempSearch.icon = 'far fa-hanukiah'"></i>
      <i class="far fa-hat-santa" v-on:click="$store.state.tempSearch.icon = 'far fa-hat-santa'"></i>
      <i class="far fa-hat-witch" v-on:click="$store.state.tempSearch.icon = 'far fa-hat-witch'"></i>
      <i class="far fa-hat-wizard" v-on:click="$store.state.tempSearch.icon = 'far fa-hat-wizard'"></i>
      <i class="far fa-haykal" v-on:click="$store.state.tempSearch.icon = 'far fa-haykal'"></i>
      <i class="far fa-heart-circle" v-on:click="$store.state.tempSearch.icon = 'far fa-heart-circle'"></i>
      <i class="far fa-heart-square" v-on:click="$store.state.tempSearch.icon = 'far fa-heart-square'"></i>
      <i class="far fa-helicopter" v-on:click="$store.state.tempSearch.icon = 'far fa-helicopter'"></i>
      <i class="far fa-helmet-battle" v-on:click="$store.state.tempSearch.icon = 'far fa-helmet-battle'"></i>
      <i class="far fa-hexagon" v-on:click="$store.state.tempSearch.icon = 'far fa-hexagon'"></i>
      <i class="far fa-hockey-mask" v-on:click="$store.state.tempSearch.icon = 'far fa-hockey-mask'"></i>
      <i class="far fa-hockey-puck" v-on:click="$store.state.tempSearch.icon = 'far fa-hockey-puck'"></i>
      <i class="far fa-hockey-sticks" v-on:click="$store.state.tempSearch.icon = 'far fa-hockey-sticks'"></i>
      <i class="far fa-holly-berry" v-on:click="$store.state.tempSearch.icon = 'far fa-holly-berry'"></i>
      <i class="far fa-home-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-home-heart'"></i>
      <i class="far fa-hood-cloak" v-on:click="$store.state.tempSearch.icon = 'far fa-hood-cloak'"></i>
      <i class="far fa-hospital" v-on:click="$store.state.tempSearch.icon = 'far fa-hospital'"></i>
      <i class="far fa-hospital-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-hospital-alt'"></i>
      <i class="far fa-hot-tub" v-on:click="$store.state.tempSearch.icon = 'far fa-hot-tub'"></i>
      <i class="far fa-hotel" v-on:click="$store.state.tempSearch.icon = 'far fa-hotel'"></i>
      <i class="far fa-house-damage" v-on:click="$store.state.tempSearch.icon = 'far fa-house-damage'"></i>
      <i class="far fa-house-flood" v-on:click="$store.state.tempSearch.icon = 'far fa-house-flood'"></i>
      <i class="far fa-ice-skate" v-on:click="$store.state.tempSearch.icon = 'far fa-ice-skate'"></i>
      <i class="far fa-icicles" v-on:click="$store.state.tempSearch.icon = 'far fa-icicles'"></i>
      <i class="far fa-igloo" v-on:click="$store.state.tempSearch.icon = 'far fa-igloo'"></i>
      <i class="far fa-images" v-on:click="$store.state.tempSearch.icon = 'far fa-images'"></i>
      <i class="far fa-jack-o-lantern" v-on:click="$store.state.tempSearch.icon = 'far fa-jack-o-lantern'"></i>
      <i class="far fa-jedi" v-on:click="$store.state.tempSearch.icon = 'far fa-jedi'"></i>
      <i class="fab fa-jedi-order" v-on:click="$store.state.tempSearch.icon = 'fab fa-jedi-order'"></i>
      <i class="far fa-joint" v-on:click="$store.state.tempSearch.icon = 'far fa-joint'"></i>
      <i class="far fa-journal-whills" v-on:click="$store.state.tempSearch.icon = 'far fa-journal-whills'"></i>
      <i class="fab fa-js" v-on:click="$store.state.tempSearch.icon = 'fab fa-js'"></i>
      <i class="fab fa-js-square" v-on:click="$store.state.tempSearch.icon = 'fab fa-js-square'"></i>
      <i class="far fa-kaaba" v-on:click="$store.state.tempSearch.icon = 'far fa-kaaba'"></i>
      <i class="far fa-key-skeleton" v-on:click="$store.state.tempSearch.icon = 'far fa-key-skeleton'"></i>
      <i class="far fa-khanda" v-on:click="$store.state.tempSearch.icon = 'far fa-khanda'"></i>
      <i class="far fa-kiss" v-on:click="$store.state.tempSearch.icon = 'far fa-kiss'"></i>
      <i class="far fa-kiss-beam" v-on:click="$store.state.tempSearch.icon = 'far fa-kiss-beam'"></i>
      <i class="far fa-kiss-wink-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-kiss-wink-heart'"></i>
      <i class="far fa-knife-kitchen" v-on:click="$store.state.tempSearch.icon = 'far fa-knife-kitchen'"></i>
      <i class="far fa-landmark-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-landmark-alt'"></i>
      <i class="far fa-laugh" v-on:click="$store.state.tempSearch.icon = 'far fa-laugh'"></i>
      <i class="far fa-laugh-beam" v-on:click="$store.state.tempSearch.icon = 'far fa-laugh-beam'"></i>
      <i class="far fa-laugh-squint" v-on:click="$store.state.tempSearch.icon = 'far fa-laugh-squint'"></i>
      <i class="far fa-laugh-wink" v-on:click="$store.state.tempSearch.icon = 'far fa-laugh-wink'"></i>
      <i class="far fa-layer-group" v-on:click="$store.state.tempSearch.icon = 'far fa-layer-group'"></i>
      <i class="far fa-leaf" v-on:click="$store.state.tempSearch.icon = 'far fa-leaf'"></i>
      <i class="far fa-leaf-heart" v-on:click="$store.state.tempSearch.icon = 'far fa-leaf-heart'"></i>
      <i class="far fa-lemon" v-on:click="$store.state.tempSearch.icon = 'far fa-lemon'"></i>
      <i class="far fa-lightbulb" v-on:click="$store.state.tempSearch.icon = 'far fa-lightbulb'"></i>
      <i class="far fa-lights-holiday" v-on:click="$store.state.tempSearch.icon = 'far fa-lights-holiday'"></i>
      <i class="fab fa-linux" v-on:click="$store.state.tempSearch.icon = 'fab fa-linux'"></i>
      <i class="far fa-lips" v-on:click="$store.state.tempSearch.icon = 'far fa-lips'"></i>
      <i class="far fa-luchador" v-on:click="$store.state.tempSearch.icon = 'far fa-luchador'"></i>
      <i class="far fa-lungs" v-on:click="$store.state.tempSearch.icon = 'far fa-lungs'"></i>
      <i class="far fa-mace" v-on:click="$store.state.tempSearch.icon = 'far fa-mace'"></i>
      <i class="far fa-magic" v-on:click="$store.state.tempSearch.icon = 'far fa-magic'"></i>
      <i class="far fa-magnet" v-on:click="$store.state.tempSearch.icon = 'far fa-magnet'"></i>
      <i class="far fa-male" v-on:click="$store.state.tempSearch.icon = 'far fa-male'"></i>
      <i class="far fa-mandolin" v-on:click="$store.state.tempSearch.icon = 'far fa-mandolin'"></i>
      <i class="far fa-map-marker-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-map-marker-alt'"></i>
      <i class="far fa-mars" v-on:click="$store.state.tempSearch.icon = 'far fa-mars'"></i>
      <i class="far fa-mars-double" v-on:click="$store.state.tempSearch.icon = 'far fa-mars-double'"></i>
      <i class="far fa-mars-stroke" v-on:click="$store.state.tempSearch.icon = 'far fa-mars-stroke'"></i>
      <i class="far fa-mars-stroke-h" v-on:click="$store.state.tempSearch.icon = 'far fa-mars-stroke-h'"></i>
      <i class="far fa-mars-stroke-v" v-on:click="$store.state.tempSearch.icon = 'far fa-mars-stroke-v'"></i>
      <i class="far fa-mask" v-on:click="$store.state.tempSearch.icon = 'far fa-mask'"></i>
      <i class="far fa-medal" v-on:click="$store.state.tempSearch.icon = 'far fa-medal'"></i>
      <i class="far fa-medkit" v-on:click="$store.state.tempSearch.icon = 'far fa-medkit'"></i>
      <i class="far fa-megaphone" v-on:click="$store.state.tempSearch.icon = 'far fa-megaphone'"></i>
      <i class="far fa-meh" v-on:click="$store.state.tempSearch.icon = 'far fa-meh'"></i>
      <i class="far fa-meh-blank" v-on:click="$store.state.tempSearch.icon = 'far fa-meh-blank'"></i>
      <i class="far fa-meh-rolling-eyes" v-on:click="$store.state.tempSearch.icon = 'far fa-meh-rolling-eyes'"></i>
      <i class="far fa-memory" v-on:click="$store.state.tempSearch.icon = 'far fa-memory'"></i>
      <i class="far fa-menorah" v-on:click="$store.state.tempSearch.icon = 'far fa-menorah'"></i>
      <i class="far fa-mercury" v-on:click="$store.state.tempSearch.icon = 'far fa-mercury'"></i>
      <i class="far fa-microchip" v-on:click="$store.state.tempSearch.icon = 'far fa-microchip'"></i>
      <i class="far fa-microscope" v-on:click="$store.state.tempSearch.icon = 'far fa-microscope'"></i>
      <i class="far fa-mistletoe" v-on:click="$store.state.tempSearch.icon = 'far fa-mistletoe'"></i>
      <i class="far fa-mobile-android-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-mobile-android-alt'"></i>
      <i class="far fa-money-bill-wave" v-on:click="$store.state.tempSearch.icon = 'far fa-money-bill-wave'"></i>
      <i class="far fa-money-check" v-on:click="$store.state.tempSearch.icon = 'far fa-money-check'"></i>
      <i class="far fa-moon-stars" v-on:click="$store.state.tempSearch.icon = 'far fa-moon-stars'"></i>
      <i class="far fa-mosque" v-on:click="$store.state.tempSearch.icon = 'far fa-mosque'"></i>
      <i class="far fa-mug-hot" v-on:click="$store.state.tempSearch.icon = 'far fa-mug-hot'"></i>
      <i class="far fa-neuter" v-on:click="$store.state.tempSearch.icon = 'far fa-neuter'"></i>
      <i class="fab fa-node-js" v-on:click="$store.state.tempSearch.icon = 'fab fa-node-js'"></i>
      <i class="far fa-octagon" v-on:click="$store.state.tempSearch.icon = 'far fa-octagon'"></i>
      <i class="far fa-om" v-on:click="$store.state.tempSearch.icon = 'far fa-om'"></i>
      <i class="far fa-omega" v-on:click="$store.state.tempSearch.icon = 'far fa-omega'"></i>
      <i class="far fa-ornament" v-on:click="$store.state.tempSearch.icon = 'far fa-ornament'"></i>
      <i class="far fa-osi" v-on:click="$store.state.tempSearch.icon = 'far fa-osi'"></i>
      <i class="far fa-palette" v-on:click="$store.state.tempSearch.icon = 'far fa-palette'"></i>
      <i class="far fa-paper-plane" v-on:click="$store.state.tempSearch.icon = 'far fa-paper-plane'"></i>
      <i class="far fa-parachute-box" v-on:click="$store.state.tempSearch.icon = 'far fa-parachute-box'"></i>
      <i class="far fa-pastafarianism" v-on:click="$store.state.tempSearch.icon = 'far fa-pastafarianism'"></i>
      <i class="far fa-peace" v-on:click="$store.state.tempSearch.icon = 'far fa-peace'"></i>
      <i class="far fa-pennant" v-on:click="$store.state.tempSearch.icon = 'far fa-pennant'"></i>
      <i class="far fa-person-sign" v-on:click="$store.state.tempSearch.icon = 'far fa-person-sign'"></i>
      <i class="far fa-piggy-bank" v-on:click="$store.state.tempSearch.icon = 'far fa-piggy-bank'"></i>
      <i class="far fa-place-of-worship" v-on:click="$store.state.tempSearch.icon = 'far fa-place-of-worship'"></i>
      <i class="far fa-plane" v-on:click="$store.state.tempSearch.icon = 'far fa-plane'"></i>
      <i class="far fa-plane-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-plane-alt'"></i>
      <i class="far fa-plus-square" v-on:click="$store.state.tempSearch.icon = 'far fa-plus-square'"></i>
      <i class="far fa-poo" v-on:click="$store.state.tempSearch.icon = 'far fa-poo'"></i>
      <i class="far fa-poop" v-on:click="$store.state.tempSearch.icon = 'far fa-poop'"></i>
      <i class="far fa-pray" v-on:click="$store.state.tempSearch.icon = 'far fa-pray'"></i>
      <i class="far fa-praying-hands" v-on:click="$store.state.tempSearch.icon = 'far fa-praying-hands'"></i>
      <i class="far fa-prescription" v-on:click="$store.state.tempSearch.icon = 'far fa-prescription'"></i>
      <i class="fab fa-python" v-on:click="$store.state.tempSearch.icon = 'fab fa-python'"></i>
      <i class="far fa-quidditch" v-on:click="$store.state.tempSearch.icon = 'far fa-quidditch'"></i>
      <i class="far fa-quran" v-on:click="$store.state.tempSearch.icon = 'far fa-quran'"></i>
      <i class="fab fa-r-project" v-on:click="$store.state.tempSearch.icon = 'fab fa-r-project'"></i>
      <i class="far fa-racquet" v-on:click="$store.state.tempSearch.icon = 'far fa-racquet'"></i>
      <i class="far fa-radiation" v-on:click="$store.state.tempSearch.icon = 'far fa-radiation'"></i>
      <i class="far fa-radiation-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-radiation-alt'"></i>
      <i class="far fa-rainbow" v-on:click="$store.state.tempSearch.icon = 'far fa-rainbow'"></i>
      <i class="fab fa-rebel" v-on:click="$store.state.tempSearch.icon = 'fab fa-rebel'"></i>
      <i class="far fa-rectangle-landscape" v-on:click="$store.state.tempSearch.icon = 'far fa-rectangle-landscape'"></i>
      <i class="far fa-rectangle-portrait" v-on:click="$store.state.tempSearch.icon = 'far fa-rectangle-portrait'"></i>
      <i class="far fa-rectangle-wide" v-on:click="$store.state.tempSearch.icon = 'far fa-rectangle-wide'"></i>
      <i class="far fa-republican" v-on:click="$store.state.tempSearch.icon = 'far fa-republican'"></i>
      <i class="far fa-ribbon" v-on:click="$store.state.tempSearch.icon = 'far fa-ribbon'"></i>
      <i class="far fa-ring" v-on:click="$store.state.tempSearch.icon = 'far fa-ring'"></i>
      <i class="far fa-rocket" v-on:click="$store.state.tempSearch.icon = 'far fa-rocket'"></i>
      <i class="far fa-route" v-on:click="$store.state.tempSearch.icon = 'far fa-route'"></i>
      <i class="far fa-route-highway" v-on:click="$store.state.tempSearch.icon = 'far fa-route-highway'"></i>
      <i class="far fa-rv" v-on:click="$store.state.tempSearch.icon = 'far fa-rv'"></i>
      <i class="far fa-sad-cry" v-on:click="$store.state.tempSearch.icon = 'far fa-sad-cry'"></i>
      <i class="far fa-sad-tear" v-on:click="$store.state.tempSearch.icon = 'far fa-sad-tear'"></i>
      <i class="far fa-satellite" v-on:click="$store.state.tempSearch.icon = 'far fa-satellite'"></i>
      <i class="far fa-scalpel" v-on:click="$store.state.tempSearch.icon = 'far fa-scalpel'"></i>
      <i class="far fa-scarecrow" v-on:click="$store.state.tempSearch.icon = 'far fa-scarecrow'"></i>
      <i class="far fa-school" v-on:click="$store.state.tempSearch.icon = 'far fa-school'"></i>
      <i class="far fa-scroll" v-on:click="$store.state.tempSearch.icon = 'far fa-scroll'"></i>
      <i class="far fa-scroll-old" v-on:click="$store.state.tempSearch.icon = 'far fa-scroll-old'"></i>
      <i class="far fa-scythe" v-on:click="$store.state.tempSearch.icon = 'far fa-scythe'"></i>
      <i class="far fa-seedling" v-on:click="$store.state.tempSearch.icon = 'far fa-seedling'"></i>
      <i class="far fa-shapes" v-on:click="$store.state.tempSearch.icon = 'far fa-shapes'"></i>
      <i class="far fa-shield" v-on:click="$store.state.tempSearch.icon = 'far fa-shield'"></i>
      <i class="far fa-shield-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-shield-alt'"></i>
      <i class="far fa-shield-cross" v-on:click="$store.state.tempSearch.icon = 'far fa-shield-cross'"></i>
      <i class="far fa-ship" v-on:click="$store.state.tempSearch.icon = 'far fa-ship'"></i>
      <i class="far fa-shoe-prints" v-on:click="$store.state.tempSearch.icon = 'far fa-shoe-prints'"></i>
      <i class="far fa-shopping-bag" v-on:click="$store.state.tempSearch.icon = 'far fa-shopping-bag'"></i>
      <i class="far fa-shopping-cart" v-on:click="$store.state.tempSearch.icon = 'far fa-shopping-cart'"></i>
      <i class="far fa-shower" v-on:click="$store.state.tempSearch.icon = 'far fa-shower'"></i>
      <i class="far fa-shuttlecock" v-on:click="$store.state.tempSearch.icon = 'far fa-shuttlecock'"></i>
      <i class="far fa-skating" v-on:click="$store.state.tempSearch.icon = 'far fa-skating'"></i>
      <i class="far fa-ski-jump" v-on:click="$store.state.tempSearch.icon = 'far fa-ski-jump'"></i>
      <i class="far fa-ski-lift" v-on:click="$store.state.tempSearch.icon = 'far fa-ski-lift'"></i>
      <i class="far fa-skiing" v-on:click="$store.state.tempSearch.icon = 'far fa-skiing'"></i>
      <i class="far fa-skiing-nordic" v-on:click="$store.state.tempSearch.icon = 'far fa-skiing-nordic'"></i>
      <i class="far fa-skull-crossbones" v-on:click="$store.state.tempSearch.icon = 'far fa-skull-crossbones'"></i>
      <i class="far fa-slash" v-on:click="$store.state.tempSearch.icon = 'far fa-slash'"></i>
      <i class="far fa-sledding" v-on:click="$store.state.tempSearch.icon = 'far fa-sledding'"></i>
      <i class="far fa-sleigh" v-on:click="$store.state.tempSearch.icon = 'far fa-sleigh'"></i>
      <i class="far fa-smile-beam" v-on:click="$store.state.tempSearch.icon = 'far fa-smile-beam'"></i>
      <i class="far fa-smile-wink" v-on:click="$store.state.tempSearch.icon = 'far fa-smile-wink'"></i>
      <i class="far fa-smoking" v-on:click="$store.state.tempSearch.icon = 'far fa-smoking'"></i>
      <i class="far fa-sms" v-on:click="$store.state.tempSearch.icon = 'far fa-sms'"></i>
      <i class="far fa-snowboarding" v-on:click="$store.state.tempSearch.icon = 'far fa-snowboarding'"></i>
      <i class="far fa-snowflake" v-on:click="$store.state.tempSearch.icon = 'far fa-snowflake'"></i>
      <i class="far fa-snowman" v-on:click="$store.state.tempSearch.icon = 'far fa-snowman'"></i>
      <i class="far fa-snowmobile" v-on:click="$store.state.tempSearch.icon = 'far fa-snowmobile'"></i>
      <i class="far fa-snowplow" v-on:click="$store.state.tempSearch.icon = 'far fa-snowplow'"></i>
      <i class="far fa-space-shuttle" v-on:click="$store.state.tempSearch.icon = 'far fa-space-shuttle'"></i>
      <i class="far fa-spade" v-on:click="$store.state.tempSearch.icon = 'far fa-spade'"></i>
      <i class="far fa-spider-web" v-on:click="$store.state.tempSearch.icon = 'far fa-spider-web'"></i>
      <i class="far fa-staff" v-on:click="$store.state.tempSearch.icon = 'far fa-staff'"></i>
      <i class="far fa-star" v-on:click="$store.state.tempSearch.icon = 'far fa-star'"></i>
      <i class="far fa-star-and-crescent" v-on:click="$store.state.tempSearch.icon = 'far fa-star-and-crescent'"></i>
      <i class="far fa-star-christmas" v-on:click="$store.state.tempSearch.icon = 'far fa-star-christmas'"></i>
      <i class="far fa-star-of-david" v-on:click="$store.state.tempSearch.icon = 'far fa-star-of-david'"></i>
      <i class="far fa-stethoscope" v-on:click="$store.state.tempSearch.icon = 'far fa-stethoscope'"></i>
      <i class="fab fa-sticker-mule" v-on:click="$store.state.tempSearch.icon = 'fab fa-sticker-mule'"></i>
      <i class="far fa-stocking" v-on:click="$store.state.tempSearch.icon = 'far fa-stocking'"></i>
      <i class="far fa-stomach" v-on:click="$store.state.tempSearch.icon = 'far fa-stomach'"></i>
      <i class="far fa-subway" v-on:click="$store.state.tempSearch.icon = 'far fa-subway'"></i>
      <i class="far fa-suitcase" v-on:click="$store.state.tempSearch.icon = 'far fa-suitcase'"></i>
      <i class="far fa-surprise" v-on:click="$store.state.tempSearch.icon = 'far fa-surprise'"></i>
      <i class="far fa-swimming-pool" v-on:click="$store.state.tempSearch.icon = 'far fa-swimming-pool'"></i>
      <i class="far fa-sword" v-on:click="$store.state.tempSearch.icon = 'far fa-sword'"></i>
      <i class="far fa-swords" v-on:click="$store.state.tempSearch.icon = 'far fa-swords'"></i>
      <i class="far fa-synagogue" v-on:click="$store.state.tempSearch.icon = 'far fa-synagogue'"></i>
      <i class="far fa-table-tennis" v-on:click="$store.state.tempSearch.icon = 'far fa-table-tennis'"></i>
      <i class="far fa-tablet-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-tablet-alt'"></i>
      <i class="far fa-tablets" v-on:click="$store.state.tempSearch.icon = 'far fa-tablets'"></i>
      <i class="far fa-taxi" v-on:click="$store.state.tempSearch.icon = 'far fa-taxi'"></i>
      <i class="far fa-teeth" v-on:click="$store.state.tempSearch.icon = 'far fa-teeth'"></i>
      <i class="far fa-teeth-open" v-on:click="$store.state.tempSearch.icon = 'far fa-teeth-open'"></i>
      <i class="far fa-tennis-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-tennis-ball'"></i>
      <i class="far fa-thumbs-down" v-on:click="$store.state.tempSearch.icon = 'far fa-thumbs-down'"></i>
      <i class="far fa-ticket" v-on:click="$store.state.tempSearch.icon = 'far fa-ticket'"></i>
      <i class="far fa-ticket-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-ticket-alt'"></i>
      <i class="far fa-tint" v-on:click="$store.state.tempSearch.icon = 'far fa-tint'"></i>
      <i class="far fa-toilet-paper" v-on:click="$store.state.tempSearch.icon = 'far fa-toilet-paper'"></i>
      <i class="far fa-toilet-paper-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-toilet-paper-alt'"></i>
      <i class="far fa-tombstone" v-on:click="$store.state.tempSearch.icon = 'far fa-tombstone'"></i>
      <i class="far fa-tombstone-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-tombstone-alt'"></i>
      <i class="far fa-tooth" v-on:click="$store.state.tempSearch.icon = 'far fa-tooth'"></i>
      <i class="far fa-torah" v-on:click="$store.state.tempSearch.icon = 'far fa-torah'"></i>
      <i class="far fa-torii-gate" v-on:click="$store.state.tempSearch.icon = 'far fa-torii-gate'"></i>
      <i class="far fa-traffic-cone" v-on:click="$store.state.tempSearch.icon = 'far fa-traffic-cone'"></i>
      <i class="far fa-traffic-light-slow" v-on:click="$store.state.tempSearch.icon = 'far fa-traffic-light-slow'"></i>
      <i class="far fa-train" v-on:click="$store.state.tempSearch.icon = 'far fa-train'"></i>
      <i class="far fa-tram" v-on:click="$store.state.tempSearch.icon = 'far fa-tram'"></i>
      <i class="far fa-transgender" v-on:click="$store.state.tempSearch.icon = 'far fa-transgender'"></i>
      <i class="far fa-transgender-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-transgender-alt'"></i>
      <i class="far fa-treasure-chest" v-on:click="$store.state.tempSearch.icon = 'far fa-treasure-chest'"></i>
      <i class="far fa-tree-christmas" v-on:click="$store.state.tempSearch.icon = 'far fa-tree-christmas'"></i>
      <i class="far fa-tree-decorated" v-on:click="$store.state.tempSearch.icon = 'far fa-tree-decorated'"></i>
      <i class="far fa-trophy-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-trophy-alt'"></i>
      <i class="far fa-truck" v-on:click="$store.state.tempSearch.icon = 'far fa-truck'"></i>
      <i class="far fa-truck-monster" v-on:click="$store.state.tempSearch.icon = 'far fa-truck-monster'"></i>
      <i class="far fa-truck-pickup" v-on:click="$store.state.tempSearch.icon = 'far fa-truck-pickup'"></i>
      <i class="far fa-truck-plow" v-on:click="$store.state.tempSearch.icon = 'far fa-truck-plow'"></i>
      <i class="far fa-tv-retro" v-on:click="$store.state.tempSearch.icon = 'far fa-tv-retro'"></i>
      <i class="far fa-umbrella" v-on:click="$store.state.tempSearch.icon = 'far fa-umbrella'"></i>
      <i class="far fa-umbrella-beach" v-on:click="$store.state.tempSearch.icon = 'far fa-umbrella-beach'"></i>
      <i class="far fa-university" v-on:click="$store.state.tempSearch.icon = 'far fa-university'"></i>
      <i class="fab fa-usb" v-on:click="$store.state.tempSearch.icon = 'fab fa-usb'"></i>
      <i class="far fa-usd-circle" v-on:click="$store.state.tempSearch.icon = 'far fa-usd-circle'"></i>
      <i class="far fa-user-circle" v-on:click="$store.state.tempSearch.icon = 'far fa-user-circle'"></i>
      <i class="far fa-usd-square" v-on:click="$store.state.tempSearch.icon = 'far fa-usd-square'"></i>
      <i class="far fa-user-crown" v-on:click="$store.state.tempSearch.icon = 'far fa-user-crown'"></i>
      <i class="far fa-user-md" v-on:click="$store.state.tempSearch.icon = 'far fa-user-md'"></i>
      <i class="far fa-user-secret" v-on:click="$store.state.tempSearch.icon = 'far fa-user-secret'"></i>
      <i class="far fa-users-crown" v-on:click="$store.state.tempSearch.icon = 'far fa-users-crown'"></i>
      <i class="far fa-venus" v-on:click="$store.state.tempSearch.icon = 'far fa-venus'"></i>
      <i class="far fa-venus-double" v-on:click="$store.state.tempSearch.icon = 'far fa-venus-double'"></i>
      <i class="far fa-venus-mars" v-on:click="$store.state.tempSearch.icon = 'far fa-venus-mars'"></i>
      <i class="far fa-vial" v-on:click="$store.state.tempSearch.icon = 'far fa-vial'"></i>
      <i class="far fa-vihara" v-on:click="$store.state.tempSearch.icon = 'far fa-vihara'"></i>
      <i class="far fa-volcano" v-on:click="$store.state.tempSearch.icon = 'far fa-volcano'"></i>
      <i class="far fa-volleyball-ball" v-on:click="$store.state.tempSearch.icon = 'far fa-volleyball-ball'"></i>
      <i class="fab fa-vuejs" v-on:click="$store.state.tempSearch.icon = 'fab fa-vuejs'"></i>
      <i class="far fa-wand" v-on:click="$store.state.tempSearch.icon = 'far fa-wand'"></i>
      <i class="far fa-wand-magic" v-on:click="$store.state.tempSearch.icon = 'far fa-wand-magic'"></i>
      <i class="far fa-warehouse" v-on:click="$store.state.tempSearch.icon = 'far fa-warehouse'"></i>
      <i class="far fa-warehouse-alt" v-on:click="$store.state.tempSearch.icon = 'far fa-warehouse-alt'"></i>
      <i class="far fa-wheelchair" v-on:click="$store.state.tempSearch.icon = 'far fa-wheelchair'"></i>
      <i class="far fa-whistle" v-on:click="$store.state.tempSearch.icon = 'far fa-whistle'"></i>
      <i class="far fa-windsock" v-on:click="$store.state.tempSearch.icon = 'far fa-windsock'"></i>
      <i class="far fa-wine-glass" v-on:click="$store.state.tempSearch.icon = 'far fa-wine-glass'"></i>
      <i class="far fa-xbox" v-on:click="$store.state.tempSearch.icon = 'far fa-xbox'"></i>
      <i class="far fa-yin-yang" v-on:click="$store.state.tempSearch.icon = 'far fa-yin-yang'"></i>
    </div>

    <div id="clear-icon" v-on:click="$store.state.tempSearch.icon = ''">
      <i class="far fa-times-circle" ></i> <span>Clear icon</span>
    </div>
  </div>
</template>

<script>
  export default {
    data: function() {
      return {
        icon: this.$store.state.tempSearch.icon || ''
      }
    }
  }
</script>
