query oauthAppMany($skip: Int, $limit: Int) {
    oauthAppMany(skip: $skip, limit: $limit) {
        id,
        client_id,
        description,
        homepage_url,
        name,
        privacy_policy_url,
        redirect_uris,
        user_id,
        user_id_string
    }
}
