query oauthAppMany($skip: Int, $limit: Int) {
    oauthAppMany(skip: $skip, limit: $limit) {
        id,
        client_id,
        description,
        homepage_url,
        name,
        privacy_policy_url,
        provider_id,
        provider_id_string,
        redirect_uris
    }
}
