query peopleMany($skip: Int, $limit: Int) {
    peopleMany(skip: $skip, limit: $limit) {
        id,
        avatar_url,
        first_name,
        middle_name,
        last_name,
        contact_ids,
        contact_id_strings,
        hydratedContacts {
        	id,
			avatar_url,
			handle,
			name
        }
    }
}
