query personOne($id: String, $self: Boolean) {
    personOne(filter: { id: $id, self: $self }) {
        id,
        avatar_url,
        first_name,
        middle_name,
        last_name,
        contact_ids,
        contact_id_strings,
        hidden,
        self,
        hydratedContacts {
        	id,
			avatar_url,
			handle,
			name,
			connection_id,
			self,
			hydratedConnection {
				id,
				provider_id,
				provider {
					id,
					name
				},
			}
        }
    }
}
