query personMany($skip: Int, $limit: Int, $sort: SortFindManyPeopleInput, $filter: FilterFindManyPeopleInput) {
    personMany(skip: $skip, limit: $limit, sort: $sort, filter: $filter) {
        id,
        avatar_url,
        external_avatar_url,
        first_name,
        middle_name,
        last_name,
        contact_ids,
        contact_id_strings,
        hidden,
        hydratedContacts {
        	id,
			avatar_url,
			handle,
			name,
			connection_id,
			hydratedConnection {
				id,
				provider_id,
				provider {
					id,
					name
				},
			}
        }
    }
}
