query searchOne($id: String!) {
    searchOne(filter: { id: $id }) {
        id,
        count,
        filters {
          data,
          name,
          type
        },
        favorited,
        icon,
        icon_color,
        query,
        name
    }
}
