query tagMany($skip: Int, $limit: Int, $sort: SortFindManyTagsInput, $filter: FilterFindManyTagsInput) {
    tagMany(skip: $skip, limit: $limit, sort: $sort, filter: $filter) {
        id,
        tag,
        share,
        passcode
    }
}
