query userCounts {
    userCounts {
        connectionCount,
        contactCount,
        contentCount,
        eventCount,
        locationCount,
        peopleCount,
        searchCount,
        favoriteSearchCount,
        tagCount,
        sharedTagCount
    }
}
